### ISSUE TITLE
XML loading broken because needle tag requirements 

### ISSUE THREAD

**Issue by panch13114** [go-smart/glossia-comparator#1]
I get the following error message, when we run the glot results -i XYZ
It says RuntimeError: Simulation definition: Needle tag has not got all information: Index 'needle1', Class 'point-sources', File 'None'. The trace back error goes to parse.py

**Comment by philtweir** [comment]
OK - will check that now

**Comment by philtweir** [comment]
Should be fixed as of 303f152 & unit tests running fine - the updates to standardize the filename had a backwards compatibility issue for pre-existing XML definitions.

**Comment by panch13114** [comment]
Thank you, it works now.
